name: integracion continua

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/ckeckout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12'
    - run: npm install
